// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv6S3Y3EBSb2bWNmJT3wbG15gUA1RG6s0',
    appId: '1:900622401215:web:7af07f5a7f3fa020b9900a',
    messagingSenderId: '900622401215',
    projectId: 'skylab-28c61',
    authDomain: 'skylab-28c61.firebaseapp.com',
    storageBucket: 'skylab-28c61.appspot.com',
    measurementId: 'G-MYDTHNHR7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5IPvqOxGexAQosNHON6wZ5htJPvcOy4',
    appId: '1:900622401215:android:3bf52e82a42d2b1ab9900a',
    messagingSenderId: '900622401215',
    projectId: 'skylab-28c61',
    storageBucket: 'skylab-28c61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFNioG6ruVdG8H9UhMEVFLjqs4ujjCzo',
    appId: '1:900622401215:ios:7900b318c42cb035b9900a',
    messagingSenderId: '900622401215',
    projectId: 'skylab-28c61',
    storageBucket: 'skylab-28c61.appspot.com',
    iosClientId: '900622401215-flbhnfrs17fj0lglbvhkniopdsjut22q.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFNioG6ruVdG8H9UhMEVFLjqs4ujjCzo',
    appId: '1:900622401215:ios:7900b318c42cb035b9900a',
    messagingSenderId: '900622401215',
    projectId: 'skylab-28c61',
    storageBucket: 'skylab-28c61.appspot.com',
    iosClientId: '900622401215-flbhnfrs17fj0lglbvhkniopdsjut22q.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerPage',
  );
}
